### ISSUE TITLE
Add Instruction Guidance - 2

### ISSUE THREAD

**Issue by sunyu912** [psych-tech/smart-pm#11]
This is in the same screen as #10 as the step 2.

The 2-line text says:
"Face Up"
"Insert the Test"

Then, in the middle, let's put another "Measure" button, so that users can trigger the test right here.

<img width="884" alt="screen shot 2017-07-21 at 10 11 39 am" src="https://user-images.githubusercontent.com/1639351/28474325-168f4d90-6dfd-11e7-8537-e5260cf6a376.png">

**Comment by er-rivera** [comment]
Commit was for #10
