### ISSUE TITLE
Screen 2 - Add New User

### ISSUE THREAD

**Issue by sunyu912** [psych-tech/smart-pm#47]
![image](https://user-images.githubusercontent.com/1639351/33387654-b0ccd624-d4e2-11e7-81e4-d9909fd0534f.png)

**Comment by sunyu912** [comment]
Name
Gender
Date of Birth
Email
Group (Don't show anything)

Checkbox - Send Report Automatically

Button - Save

**Comment by sunyu912** [comment]
Is this one done?

**Comment by er-rivera** [comment]
I am unsure on how to add gender and group for a user as those properties aren't available for our current EmoUser.

**Comment by sunyu912** [comment]
That's ok. You can just put the UI element there without using the data for
the backend.
