### ISSUE TITLE
Investigate the Bottom Black Scanned Id

### ISSUE THREAD

**Issue by sunyu912** [psych-tech/smart-pm#59]
When did this start to show up? It might be related with their library, but did you see it last time?

![bug5](https://user-images.githubusercontent.com/1639351/34643394-88267838-f2d8-11e7-918d-57a6dfdea013.png)

**Comment by er-rivera** [comment]
A setting was activated in BCR Service app when debugging the camera module. Black box removed once settings were changed in BCR service app.
